### PR TITLE
New offload

### PR DESCRIPTION
**Pull request by jmohdyusof**
This branch was up to date with master 3/19. All C and Fortran tests pass with gcc on Darwin.

---
This change is [Reviewable](https://reviewable.io/reviews/lanl/bml/369)

### CODE REVIEW

**Comment by nicolasbock** [comment]
Rebased. I'll got through it more carefully now.

**Comment by nicolasbock** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          8 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please limit commit subject line to 50 characters.<br />
63cce27b93255829d98e599fcc77ddfd4b010c33</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please remove period from end of commit subject line.<br />
63cce27b93255829d98e599fcc77ddfd4b010c33</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please limit commit subject line to 50 characters.<br />
4162342ba03d9e7f11d8b482becb1cfb7e826c85</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please remove period from end of commit subject line.<br />
4162342ba03d9e7f11d8b482becb1cfb7e826c85</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please limit commit subject line to 50 characters.<br />
c009b667f8810432c6da774c8469ca244a49b7f3</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please remove period from end of commit subject line.<br />
c009b667f8810432c6da774c8469ca244a49b7f3</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please limit commit subject line to 50 characters.<br />
37c9a128f5c94cd1d38acb9c7cb7af7d28edb849</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please remove period from end of commit subject line.<br />
37c9a128f5c94cd1d38acb9c7cb7af7d28edb849</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jmohdyusof** [comment]
Let me know if I need to do anything. The 'errors' related to me being too descriptive in my comments seem strange.

**Comment by nicolasbock** [comment]
That's our super smart linter :wink: I reworded some of those commit messages so that the linter is hopefully a little happier.

**Comment by jmohdyusof** [comment]
Cool. I really should have separated out the get_element changes in a separate commit, glad it didn't cause too many problems.

**Pull request merged**
