### PR TITLE
Cleanup MPI init/finalize

### PR DESCRIPTION
**Pull request by jeanlucf22**
Even though we are not using it now, a few things were not right with MPI calls and needed to be fixed before we can start developing a distributed BML capability

---
This change is [Reviewable](https://reviewable.io/reviews/lanl/bml/411)

### CODE REVIEW

**Review by nicolasbock — COMMENTED** [review]
Thanks @jeanlucf22 ! Could you add your pull request description to the commit message? The commit message is part of the repository while the pull request is not. Thanks!

**Comment by nicolasbock** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please remove period from end of commit subject line.<br />
d2c01d3fd1d8424ff841e6535cbe1b74201566f3</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jeanlucf22** [comment]
This PR is ready for review

**Review by nicolasbock — APPROVED** [review]
Thanks @jeanlucf22

**Pull request merged**
