### PR TITLE
CSR integration

### PR DESCRIPTION
**Pull request by oseikuffuor1**
This PR adds CSR integration into BML. All functionalities supported by the ellblock format is enabled for CSR as well. Additional functionality may be added as needed. This implementation is meant for CPU only. It also utilizes CPU-based openmp. GPU integration will use vendor provided kernels when possible, and follow the openMP offload constructs used for ellpack.

---
This change is [Reviewable](https://reviewable.io/reviews/lanl/bml/378)

### CODE REVIEW

**Comment by nicolasbock** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          2 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please use more than one word.<br />
0f88149979e7925558f1b76a31f3a8e90e1cccdd</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please rebase to get rid of the merge commits in this PR</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by oseikuffuor1** [comment]
@nicolasbock for getting rid of the merge commits, do you mean changing the commit message or removing the commit completely?

**Comment by jeanlucf22** [comment]
@oseikuffuor1 looks like you need to rebase your branch first, and then apply code formatting

**Comment by nicolasbock** [comment]
Yes, basically make the commit history linear @oseikuffuor1 . To untangle that will take a little work though.

**Comment by nicolasbock** [comment]
Also, such a large PR is really difficult to review. Do you think you could split it into smaller ones?

**Comment by oseikuffuor1** [comment]
@nicolasbock Ok I will try to break this up into multiple PRs. I will close this PR for now. Also, since PR #377 is not merged yet, I would suggest waiting on that since I had already incorporated those changes before the PR was submitted.

**Comment by oseikuffuor1** [comment]
Closing this PR. Will resubmit in multiple requests.

**Comment by nicolasbock** [comment]
Thanks!

**Pull request closed without merging**
