### PR TITLE
Add mixed clang/gcc tests

### PR DESCRIPTION
**Pull request by nicolasbock**
Signed-off-by: Nicolas Bock <nicolasbock@gmail.com>

### CODE REVIEW

**Comment by nicolasbock** [comment]
@awvwgk While I figure out how to build on OS X I added a mixed clang/gcc test to Linux.

**Review by jeanlucf22 — COMMENTED** [review]
why 'gcc-9' in the names of these new scripts? Should it be 'gfortran9'?
Also, could it be using flang instead of gfortran?

**Comment by nicolasbock** [comment]
> why 'gcc-9' in the names of these new scripts? Should it be 'gfortran9'?

Yes, I can definitely change it. I had meant `gcc` more as the GNU compiler collection generically and not specifically as their C compiler. But the naming should as clear as possible and `gfortran-9` would indicate perhaps more clearly that it's only the Fortran part that is using GCC.

> Also, could it be using flang instead of gfortran?

Yes, that might be more sensible. I'll change that as well.

Thanks!

**Comment by nicolasbock** [comment]
> > Also, could it be using flang instead of gfortran?
> 
> Yes, that might be more sensible. I'll change that as well.

So far I haven't found any `flang` packages. Are you using `flang`? How do you install it if you do?

**Comment by jeanlucf22** [comment]
I don't write much fortran myself, so I don't know. But I am ok with clang + gfortran if they work well together.

**Review by cnegre — APPROVED** [review]

**Pull request merged**
