### PR TITLE
Distributed2d diagonalization and norm functions

### PR DESCRIPTION
**Pull request by jeanlucf22**
Diagonalization requires ScaLAPACK.
ScaLAPACK library should be specified using
export EXTRA_LINK_FLAGS=...
since cmake build has currently not capability to find it.

### CODE REVIEW

**Review by suemni — APPROVED** [review]

**Review by nicolasbock — APPROVED** [review]
It would be nice if we could test this change on CI.

**Comment by jeanlucf22** [comment]
> It would be nice if we could test this change on CI.

That would require ScaLapack added to the CI build. @nicolasbock do you know how to do that? I don't...

**Comment by nicolasbock** [comment]
> > It would be nice if we could test this change on CI.
> 
> That would require ScaLapack added to the CI build. @nicolasbock do you know how to do that? I don't...

Let's merge this and I'll add scalapack to CI so we can start testing it. In case something breaks you are on the hook to fixing it @jeanlucf22 :smile:

**Comment by nicolasbock** [comment]
Could you rebase this change on top of the current `master` to resolve the merge conflict @jeanlucf22 ?

**Comment by jeanlucf22** [comment]
> Could you rebase this change on top of the current `master` to resolve the merge conflict @jeanlucf22 ?

Done

**Comment by nicolasbock** [comment]
Thanks @jeanlucf22 !

**Pull request merged**
