### PR TITLE
Accelerated GPU offload bml_add_ellpack and bml_multiply_ellpack via …

### PR DESCRIPTION
**Pull request by mewall**
…teams distribute pragmas

### CODE REVIEW

**Review by nicolasbock — APPROVED** [review]
The code looks good but I don't have any hardware to test it on.

**Comment by mewall** [comment]
Someone else might want to test as well, but below are some profiles for a v100 using the new vs old code (>55-fold speedup for multiply, 41-fold speedup for add). -- Mike


New code:


***@***.*** build]$ nvprof tests/C-tests/bml-test -n multiply -t ellpack -p single_real -N 1000 > test.lgo==31442== NVPROF is profiling process 31442, command: tests/C-tests/bml-test -n multiply -t ellpack -p single_real -N 1000

multiply

N = 1000

==31442== Profiling application: tests/C-tests/bml-test -n multiply -t ellpack -p single_real -N 1000

==31442== Profiling result:

            Type  Time(%)      Time     Calls       Avg       Min       Max  Name

 GPU activities:   96.66%  364.96ms         1  364.96ms  364.96ms  364.96ms  bml_multiply_AB_ellpack_single_real$_omp_fn$0

                    1.20%  4.5357ms        15  302.38us  1.6640us  490.08us  [CUDA memcpy DtoH]

                    0.95%  3.5690ms        20  178.45us  1.1520us  678.65us  [CUDA memcpy HtoD]

                    0.48%  1.8092ms         1  1.8092ms  1.8092ms  1.8092ms  bml_add_ellpack_single_real$_omp_fn$0

                    0.45%  1.6827ms         3  560.90us  555.90us  567.96us  bml_zero_matrix_ellpack_single_real$_omp_fn$2

                    0.26%  997.40us         3  332.47us  327.93us  338.33us  bml_zero_matrix_ellpack_single_real$_omp_fn$0

      API calls:   42.18%  369.48ms         8  46.185ms  331.17us  364.96ms  cuCtxSynchronize

                   23.42%  205.20ms         1  205.20ms  205.20ms  205.20ms  cuCtxCreate

                   18.29%  160.22ms        57  2.8109ms  2.3447ms  8.7711ms  cuLinkAddData

                    9.07%  79.490ms         1  79.490ms  79.490ms  79.490ms  cuCtxDestroy

                    2.45%  21.449ms         1  21.449ms  21.449ms  21.449ms  cuLinkComplete

                    1.93%  16.922ms         1  16.922ms  16.922ms  16.922ms  cuModuleLoadData

                    0.80%  6.9859ms        28  249.50us  6.9400us  1.0402ms  cuMemAlloc

                    0.75%  6.5405ms        15  436.04us  14.606us  701.37us  cuMemcpyDtoH

                    0.56%  4.9490ms        20  247.45us  10.193us  968.31us  cuMemcpyHtoD

                    0.27%  2.3861ms         8  298.26us  13.346us  2.2748ms  cuLaunchKernel

                    0.25%  2.1508ms        19  113.20us  3.7270us  328.88us  cuMemFree

                    0.01%  68.207us        16  4.2620us     131ns  63.349us  cuDeviceGetAttribute

                    0.01%  45.459us        84     541ns     284ns  3.6490us  cuModuleGetFunction

                    0.00%  40.017us         1  40.017us  40.017us  40.017us  cuLinkCreate

                    0.00%  28.784us        69     417ns     114ns  6.0880us  cuCtxGetDevice

                    0.00%  25.532us        35     729ns     343ns  1.9980us  cuMemGetAddressRange

                    0.00%  23.896us       168     142ns     120ns     353ns  cuFuncGetAttribute

                    0.00%  16.445us         1  16.445us  16.445us  16.445us  cuDeviceGetName

                    0.00%  9.3840us         1  9.3840us  9.3840us  9.3840us  cuDeviceGetPCIBusId

                    0.00%  3.0730us         1  3.0730us  3.0730us  3.0730us  cuLinkDestroy

                    0.00%  2.6970us         2  1.3480us     167ns  2.5300us  cuDeviceGet

                    0.00%  2.4060us         1  2.4060us  2.4060us  2.4060us  cuModuleGetGlobal

                    0.00%  1.4750us         4     368ns     114ns  1.0580us  cuDeviceGetCount

                    0.00%  1.3320us         1  1.3320us  1.3320us  1.3320us  cuCtxGetCurrent

                    0.00%     844ns         1     844ns     844ns     844ns  cuInit

                    0.00%     120ns         1     120ns     120ns     120ns  cuDriverGetVersion


And using the old code:


***@***.*** build]$ nvprof tests/C-tests/bml-test -n multiply -t ellpack -p single_real -N 1000 > test.ogo

==37499== NVPROF is profiling process 37499, command: tests/C-tests/bml-test -n multiply -t ellpack -p single_real -N 1000

multiply

N = 1000

==37499== Profiling application: tests/C-tests/bml-test -n multiply -t ellpack -p single_real -N 1000

==37499== Profiling result:

            Type  Time(%)      Time     Calls       Avg       Min       Max  Name

 GPU activities:   99.58%  20.3514s         1  20.3514s  20.3514s  20.3514s  bml_multiply_AB_ellpack_single_real$_omp_fn$0

                    0.36%  74.218ms         1  74.218ms  74.218ms  74.218ms  bml_add_ellpack_single_real$_omp_fn$0

                    0.02%  4.4844ms        21  213.54us  1.3760us  481.21us  [CUDA memcpy DtoH]

                    0.02%  3.5331ms        20  176.65us  1.1200us  649.50us  [CUDA memcpy HtoD]

                    0.01%  1.6787ms         3  559.56us  558.27us  562.11us  bml_zero_matrix_ellpack_single_real$_omp_fn$2

                    0.00%  1.0018ms         3  333.92us  332.45us  336.41us  bml_zero_matrix_ellpack_single_real$_omp_fn$0

      API calls:   97.34%  20.4284s         8  2.55355s  335.61us  20.3514s  cuCtxSynchronize

                    1.11%  232.66ms         1  232.66ms  232.66ms  232.66ms  cuCtxCreate

                    0.91%  190.60ms        57  3.3439ms  2.1537ms  46.599ms  cuLinkAddData

                    0.36%  74.644ms         1  74.644ms  74.644ms  74.644ms  cuCtxDestroy

                    0.10%  20.329ms         1  20.329ms  20.329ms  20.329ms  cuLinkComplete

                    0.08%  16.580ms         1  16.580ms  16.580ms  16.580ms  cuModuleLoadData

                    0.04%  7.3955ms        21  352.17us  12.065us  1.0100ms  cuMemcpyDtoH

                    0.03%  5.8883ms        28  210.30us  6.4410us  1.0417ms  cuMemAlloc

                    0.02%  4.9625ms        20  248.13us  10.571us  966.37us  cuMemcpyHtoD

                    0.02%  3.1608ms        19  166.36us  4.0770us  1.5353ms  cuMemFree

                    0.01%  2.5425ms         8  317.81us  13.204us  2.3533ms  cuLaunchKernel

                    0.00%  62.320us        16  3.8950us     121ns  56.981us  cuDeviceGetAttribute

                    0.00%  42.498us        84     505ns     291ns  3.1140us  cuModuleGetFunction

                    0.00%  41.633us        41  1.0150us     286ns  13.071us  cuMemGetAddressRange

                    0.00%  41.433us         1  41.433us  41.433us  41.433us  cuLinkCreate

                    0.00%  31.220us        75     416ns     114ns  4.1090us  cuCtxGetDevice

                    0.00%  24.565us       168     146ns     128ns     351ns  cuFuncGetAttribute

                    0.00%  15.275us         1  15.275us  15.275us  15.275us  cuDeviceGetName

                    0.00%  11.424us         1  11.424us  11.424us  11.424us  cuDeviceGetPCIBusId

                    0.00%  3.7760us         2  1.8880us     159ns  3.6170us  cuDeviceGet

                    0.00%  3.0780us         1  3.0780us  3.0780us  3.0780us  cuLinkDestroy

                    0.00%  2.3660us         4     591ns     125ns  1.8790us  cuDeviceGetCount

                    0.00%  2.3420us         1  2.3420us  2.3420us  2.3420us  cuModuleGetGlobal

                    0.00%  1.7100us         1  1.7100us  1.7100us  1.7100us  cuCtxGetCurrent

                    0.00%  1.4370us         1  1.4370us  1.4370us  1.4370us  cuInit

                    0.00%     119ns         1     119ns     119ns     119ns  cuDriverGetVersion



________________________________
From: Nicolas Bock ***@***.***>
Sent: Sunday, May 2, 2021 1:46:10 AM
To: lanl/bml
Cc: Wall, Michael E; Assign
Subject: [EXTERNAL] Re: [lanl/bml] Accelerated GPU offload bml_add_ellpack and bml_multiply_ellpack via … (#478)


@nicolasbock approved this pull request.

The code looks good but I don't have any hardware to test it on.

**Comment by jmohdyusof** [comment]
I tested and I get 'error code 1' for larger matrix sizes?

**Comment by jmohdyusof** [comment]
I am really confused. This looks like the standard 'target teams distribute' pragmas that I added a year ago? Did they get deleted somehow?

**Comment by mewall** [comment]
I don't know what was there, but the pragmas are not in the master branch now.


Do you want to restore them using your code? Meet to make sure my code does everything yours did? My code currently doesn't support offload using XL compilers, for example.

________________________________
From: Jamal Mohd-Yusof ***@***.***>
Sent: Monday, May 3, 2021 5:23:49 AM
To: lanl/bml
Cc: Wall, Michael E; Assign
Subject: [EXTERNAL] Re: [lanl/bml] Accelerated GPU offload bml_add_ellpack and bml_multiply_ellpack via … (#478)


I am really confused. This looks like the standard 'target teams distribute' pragmas that I added a year ago? Did they get deleted somehow?

**Comment by mewall** [comment]
The test is actually failing for N=1000, I think that's the error you're seeing:


abs(A[0]-B[0]) = 1.831055e-04


The error tolerance should probably be increased for larger matrices.


BTW, for larger matrices (e.g. N=5000), it takes a very long time for the test to complete, due to the printing of the dense matrices. Probably the test should be modified, e.g. to only print the first ~10 rows of the matrix.

________________________________
From: Jamal Mohd-Yusof ***@***.***>
Sent: Monday, May 3, 2021 5:17:51 AM
To: lanl/bml
Cc: Wall, Michael E; Assign
Subject: [EXTERNAL] Re: [lanl/bml] Accelerated GPU offload bml_add_ellpack and bml_multiply_ellpack via … (#478)


I tested and I get 'error code 1' for larger matrix sizes?

**Comment by jmohdyusof** [comment]
Yeah, I deleted my comment because it was just the error tolerance. Predictably the double precision test fails at larger sizes but the essential problem is the same. 

My local version also only prints the first few (max_row, max_col) indices to make the large tests usable. 

I don't see any real reason to roll this back, it should just make the diff smaller when I try (again?) to add the merge-based tests. Is there supposed to be a setting for teams? I don't see it being set anywhere and my version takes 23s to do a N=1000 multiply as measured by nvprof

**Comment by mewall** [comment]
I broke out the optimization work as a separate pull request.


When this is merged into master I'll rebase the jlse_intel branch on it, that's where I had added the teams. I still need to work on that some more before that code can be merged.


Does your local version take 23 secs or is it the offload_accel version? The 23 secs time is very similar to what I was seeing prior to the optimization in the pull request.

________________________________
From: Jamal Mohd-Yusof ***@***.***>
Sent: Monday, May 3, 2021 9:42:41 AM
To: lanl/bml
Cc: Wall, Michael E; Assign
Subject: [EXTERNAL] Re: [lanl/bml] Accelerated GPU offload bml_add_ellpack and bml_multiply_ellpack via … (#478)


Yeah, I deleted my comment because it was just the error tolerance. Predictably the double precision test fails at larger sizes but the essential problem is the same.

My local version also only prints the first few (max_row, max_col) indices to make the large tests usable.

I don't see any real reason to roll this back, it should just make the diff smaller when I try (again?) to add the merge-based tests. Is there supposed to be a setting for teams? I don't see it being set anywhere and my version takes 23s to do a N=1000 multiply as measured by nvprof

**Comment by jmohdyusof** [comment]
I was running the master branch; I misread the approval above as being merged with the master. Will retest with the offload_accel version.

**Comment by jmohdyusof** [comment]
@mewall is it OK if I add the print thresholding to this branch (allocate, multiply, add, transpose tests) before the merge?

**Comment by nicolasbock** [comment]
> @mewall is it OK if I add the print thresholding to this branch (allocate, multiply, add, transpose tests) before the merge?

I would prefer if you committed this change in a separate PR so we can see and test this change independently from this PR here. Once that new PR is merged you just have to rebase this one here.

**Comment by mewall** [comment]
> > @mewall is it OK if I add the print thresholding to this branch (allocate, multiply, add, transpose tests) before the merge?
> 
> I would prefer if you committed this change in a separate PR so we can see and test this change independently from this PR here. Once that new PR is merged you just have to rebase this one here.

I have rebased this on the print modification PR. 

@jmohdyusof are you OK with this PR or do you want to try to recover whatever you had done to address the same issue?

**Comment by mewall** [comment]
> @mewall AFAICT this is a subset of the commits I (thought I had) made a long time ago, so it will cause no problems if I try to recover those changes. I would go ahead and merge and then we can move on.

Thanks. Someone else (@nicolasbock ?) will need to merge as I don't have permissions.

**Pull request merged**
