### PR TITLE
Add memory pool for ellblock

### PR DESCRIPTION
**Pull request by jeanlucf22**
This change is [Reviewable](https://reviewable.io/reviews/lanl/bml/398)

### CODE REVIEW

**Comment by jeanlucf22** [comment]
@tokshgithub I am trying to allocate memory upfront to avoid a memory allocation for every single block when they come into play. Open to suggestions if you see flaws with the way I do it.

**Comment by nicolasbock** [comment]
@jeanlucf22 I'd be interested in any performance comparisons you might have. How much faster is pre-allocating?

**Comment by jeanlucf22** [comment]
@nicolasbock I will check performance now that I fixed all the bugs. If performance is much better, I will remove the [WIP] label and propose to merge this branch. Otherwise, I may put in compile time flags to choose between old way and new way of allocating memory

**Comment by nicolasbock** [comment]
Perfect, thanks!

**Comment by jeanlucf22** [comment]
It looks like using a memory pool doesn't affect performance much. But this is still useful, potentially for GPU offload.
Thus I made it a compile time option to use or not use the memory pool. It is ON by default.

**Comment by jeanlucf22** [comment]
Ready to be merged!

**Pull request merged**
