### PR TITLE
Add workflow to check for stale issues and PRs

### PR DESCRIPTION
**Pull request by nicolasbock**
Signed-off-by: Nicolas Bock <nicolasbock@gmail.com>

### CODE REVIEW

**Review by jeanlucf22 — CHANGES_REQUESTED** [review]
I would choose longer time periods for closing if no activity given that no one is working full time on that code

**Comment by nicolasbock** [comment]
Yes definitely @jeanlucf22 . How about 180 days? Or is that too excessive?

**Comment by jeanlucf22** [comment]
> 

90 days?

**Review by suemni — APPROVED** [review]

**Comment by nicolasbock** [comment]
> > 

90 days? 

Yes, that sounds like a good compromise.

**Comment by jeanlucf22** [comment]
> > 90 days?
> 
> Yes, that sounds like a good compromise.

I would also make comments match actual numbers, and increase the days-before-close to 30

**Comment by nicolasbock** [comment]
I updated the comments.

**Comment by nicolasbock** [comment]
Could you have another look @jeanlucf22 ? Thanks!

**Comment by jeanlucf22** [comment]
> Could you have another look @jeanlucf22 ? Thanks!

I would like to see the "days-before-close" to be higher than 7, maybe 20 or 30.
I was also expecting other people to comment if they have concerns...

**Comment by jeanlucf22** [comment]
> Also, should we close PRs after some time just as this would close issues? Maybe the same, after a grace period of 30 (?) days?

Would it affect the branch connected to a PR? If not, a PR can be removed safely and a new PR can be resubmitted later if appropriate.

**Comment by nicolasbock** [comment]
As far as I know it wouldn't affect the branch.

**Comment by nicolasbock** [comment]
@mewall The workflow would delete the PR. It shouldn't matter who created it. The idea here is to automate these kinds of "spring cleaning" activities and to not involve humans if possible.

**Review by jeanlucf22 — APPROVED** [review]

**Comment by mewall** [comment]
@nicolasbock I understand, I just think it's better policy to delete PRs manually, and that this doesn't require much effort in the case of BML.

________________________________
From: Nicolas Bock ***@***.***>
Sent: Thursday, December 2, 2021 11:44:43 AM
To: lanl/bml
Cc: Wall, Michael E; Mention
Subject: [EXTERNAL] Re: [lanl/bml] Add workflow to check for stale issues and PRs (PR #565)


@mewall<https://github.com/mewall> The workflow would delete the PR. It shouldn't matter who created it. The idea here is to automate these kinds of "spring cleaning" activities and to not involve humans if possible.

**Comment by nicolasbock** [comment]
True, it shouldn't be too much effort in this repository. I will update the PR and disable the closing of pull requests.

**Pull request merged**
