### PR TITLE
Fix OMP offload build memory leaks

### PR DESCRIPTION
**Pull request by mewall**
o bml_add_ellpack arrays allocated but not freed
o bml_multiply_ellpack arrays allocated but not freed o Also increase efficiency of a target region in bml_prune_rocsparse_ellpack

### CODE REVIEW

**Review by nicolasbock — APPROVED** [review]

**Review by jeanlucf22 — COMMENTED** [review]
I don't understand the changes in formatting... It is passing the tests as is, but was also passing the tests before.

**Comment by mewall** [comment]
> I don't understand the changes in formatting... It is passing the tests as is, but was also passing the tests before.

Me neither. I just ran indent in the docker container and that's what it came up with...

**Comment by jmohdyusof** [comment]
What don't you understand? I see the old version had incorrect indents (not multiple of 4) plus missing spaces after commas etc. In Python the linters do weird line breaks sometimes, but I didn't see anything obvious here (but there are a lot of lines)

**Comment by mewall** [comment]
For me the odd thing is that the lint test was previously passing...there were some error messages when I ran indent, maybe it's related to that.

________________________________
From: Jamal Mohd-Yusof ***@***.***>
Sent: Thursday, June 29, 2023 10:48:20 AM
To: lanl/bml
Cc: Wall, Michael E; Author
Subject: [EXTERNAL] Re: [lanl/bml] Fix OMP offload build memory leaks (PR #720)


What don't you understand? I see the old version had incorrect indents (not multiple of 4) plus missing spaces after commas etc. In Python the linters do weird line breaks sometimes, but I didn't see anything obvious here (but there are a lot of lines)

**Comment by jmohdyusof** [comment]
I have seen things like this when the local line length limit is different across machines so one linter breaks the line and then it gets unwrapped in github. 
The main changes look to be the 'enter data' and 'target' clauses being added, plus the addition of the 'exit data' and deallocation of arrays?

**Comment by mewall** [comment]
Yes, you're correct about the main changes.

________________________________
From: Jamal Mohd-Yusof ***@***.***>
Sent: Thursday, June 29, 2023 10:55:23 AM
To: lanl/bml
Cc: Wall, Michael E; Author
Subject: [EXTERNAL] Re: [lanl/bml] Fix OMP offload build memory leaks (PR #720)


I have seen things like this when the local line length limit is different across machines so one linter breaks the line and then it gets unwrapped in github.
The main changes look to be the 'enter data' and 'target' clauses being added, plus the addition of the 'exit data' and deallocation of arrays?

**Comment by jmohdyusof** [comment]
Was the enter/exit data missing for all the offload options or just for rocm? If for all, we probably should sweep the code and check for similar errors.

**Comment by mewall** [comment]
Let me check. If there are other errors they should be addressed in this PR.

________________________________
From: Jamal Mohd-Yusof ***@***.***>
Sent: Thursday, June 29, 2023 11:03:10 AM
To: lanl/bml
Cc: Wall, Michael E; Author
Subject: [EXTERNAL] Re: [lanl/bml] Fix OMP offload build memory leaks (PR #720)


Was the enter/exit data missing for all the offload options or just for rocm? If for all, we probably should sweep the code and check for similar errors.

**Comment by jmohdyusof** [comment]
Just to make sure I am clear, these are local work arrays that need to persist for a while, not the original arrays that should be allocated in allocate_typed or wherever?

**Comment by mewall** [comment]
They're local arrays that are just needed within the subroutines for the calculations being performed.

________________________________
From: Jamal Mohd-Yusof ***@***.***>
Sent: Thursday, June 29, 2023 11:09:32 AM
To: lanl/bml
Cc: Wall, Michael E; Author
Subject: [EXTERNAL] Re: [lanl/bml] Fix OMP offload build memory leaks (PR #720)


Just to make sure I am clear, these are local work arrays that need to persist for a while, not the original arrays that should be allocated in allocate_typed or wherever?

**Comment by jmohdyusof** [comment]
OK, so probably there isn't a similar issue in other routines, but doesn't hurt to check. Thx!

**Comment by mewall** [comment]
Indentation of typed sources is suppressed in indent.sh, which is what the CI uses for the lint check. I was indenting the *_typed.c files without using the script.


I will back out the indent changes.


    # Do not indent typed sources. indent-2.2.12 has a regression
    # https://lists.gnu.org/archive/html/bug-indent/2023-04/msg00000.html and
    # incorrectly aligns the indirection operator `*` in some cases.
    if [[ ${file} =~ typed.c ]]; then
        continue
    fi



________________________________
From: Jamal Mohd-Yusof ***@***.***>
Sent: Thursday, June 29, 2023 11:18:17 AM
To: lanl/bml
Cc: Wall, Michael E; Author
Subject: [EXTERNAL] Re: [lanl/bml] Fix OMP offload build memory leaks (PR #720)


OK, so probably there isn't a similar issue in other routines, but doesn't hurt to check. Thx!

**Comment by mewall** [comment]
> OK, so probably there isn't a similar issue in other routines, but doesn't hurt to check. Thx!

I found some other offload build routines where it was needed, ones that aren't used by the progress benchmark.

The latest revision addresses these other cases.

**Comment by mewall** [comment]
> I don't understand the changes in formatting... It is passing the tests as is, but was also passing the tests before.

I found we aren't lint checking the *_typed.c files. I backed out the formatting changes so we can address this as a separate issue. We might want to see whether we can start lint checking these files again in the future.

**Comment by mewall** [comment]
@jeanlucf22 @nicolasbock Can this be merged? I have another PR based on this branch that I'd like to initiate, I'd like to do that after this is merged to avoid any confusion with the diffs.

**Review by jeanlucf22 — APPROVED** [review]

**Pull request merged**
