### PR TITLE
Update add identity

### PR DESCRIPTION
**Pull request by oseikuffuor1**
This PR applies updates to optimize the bml-add-identity function for the sparse different formats. It also enables the use of openMP for the bml-add-csr function.

---
This change is [Reviewable](https://reviewable.io/reviews/lanl/bml/408)

### CODE REVIEW

**Review by suemni — APPROVED** [review]

**Review by nicolasbock — CHANGES_REQUESTED** [review]
Could you have a look at this failure: https://travis-ci.org/github/lanl/bml/jobs/729733477#L3614 @oseikuffuor1 ?

**Comment by oseikuffuor1** [comment]
> Could you have a look at this failure: https://travis-ci.org/github/lanl/bml/jobs/729733477#L3614 @oseikuffuor1 ?

Done. Thanks @nicolasbock

**Review by nicolasbock — CHANGES_REQUESTED** [review]
Much better @oseikuffuor1 . The `C-inverse-csr-double_complex` test is failing (https://travis-ci.org/github/lanl/bml/jobs/730029789#L4482). Maybe we need to increase the tolerance?

**Comment by oseikuffuor1** [comment]
> Much better @oseikuffuor1 . The `C-inverse-csr-double_complex` test is failing (https://travis-ci.org/github/lanl/bml/jobs/730029789#L4482). Maybe we need to increase the tolerance?

I am not sure why this is failing, as I did not make any changes to the inverse routine. I am still trying to figure out why.

**Comment by oseikuffuor1** [comment]
@nicolasbock I tried the master branch as well, it is seems to have the same issue (I used gcc-9.2). I reduced the tolerance to 1.0e-10 and that passed. I will look into this further to see if I can make sense of it.

**Comment by nicolasbock** [comment]
Thanks @oseikuffuor1 for looking into this. It's strange that this test is failing now, especially given that it's a serial job which tend to be pretty stable in my experience.

**Comment by oseikuffuor1** [comment]
> Thanks @oseikuffuor1 for looking into this. It's strange that this test is failing now, especially given that it's a serial job which tend to be pretty stable in my experience.

@nicolasbock can you review this PR again and merge if approved? I changed the relative tolerance to fix the CI failure issue. It appears to be dependent on which compiler is used. Thanks.

**Review by cnegre — APPROVED** [review]

**Review by nicolasbock — APPROVED** [review]

**Pull request merged**
