### PR TITLE
Add rocSPARSE method for ellpack multiply

### PR DESCRIPTION
**Pull request by mewall**
o Mods to types and allocations for rocSPARSE
  o Build script and cmake mods for rocSPARSE
    - Introduce BML_ROCSPARSE macro to control build
  o Add bml_multiply_rocsparse_ellpack()
    - Based on bml_multiply_cusparse_ellpack()
    - However, supports full alpha*A*B + beta*C

### CODE REVIEW

**Review by suemni — APPROVED** [review]

**Review by oseikuffuor1 — COMMENTED** [review]
Thanks @mewall! This looks good to me. One minor observation is that the changes to the condition BML_OFFLOAD_ARCH without CUDAToolkit_FOUND or hip_FOUND will now generate a build error and force the user to correct their build script (See [here](https://github.com/lanl/bml/blob/67f84c34a3d429264abd8c492915f64f6e54c2bc/CMakeLists.txt#L238-L245)). Previously, I believe the behavior was to turn off offload and continue (see [here](https://github.com/lanl/bml/blob/67f84c34a3d429264abd8c492915f64f6e54c2bc/CMakeLists.txt#L238-L245)). This new behavior is fine with me, but I just wanted to make sure this is what you had planned. Or am I missing something?

**Comment by mewall** [comment]
Yes, that was intentional as I had seen some discussion about making the build fail if what's being asked for couldn't be done, rather than generating a working build that does something different from what was intended. So, I was trying to better align the behavior with that idea. I'm open to however we want to handle these things, however. I'll leave it as is unless someone has a preference.

________________________________
From: Daniel Osei-Kuffuor ***@***.***>
Sent: Thursday, July 21, 2022 11:26:19 AM
To: lanl/bml
Cc: Wall, Michael E; Author
Subject: [EXTERNAL] Re: [lanl/bml] Add rocSPARSE method for ellpack multiply (PR #645)


@oseikuffuor1 commented on this pull request.

Thanks Mike! This looks good to me. One minor observation is that the changes to the condition BML_OFFLOAD_ARCH without CUDAToolkit_FOUND or hip_FOUND will now generate a build error and force the user to correct their build script (See here<https://urldefense.com/v3/__https://github.com/lanl/bml/blob/67f84c34a3d429264abd8c492915f64f6e54c2bc/CMakeLists.txt*L238-L245__;Iw!!Bt8fGhp8LhKGRg!A8rKQZi3hdG2P0LBkfVo6Bknwx2W7_ioXP9Qr5KOtb-M5qcfRVgWpRji_DzEpIRY-mhQgXyUDinSlg7oCUbBnk3F$>). Previously, I believe the behavior was to turn off offload and continue (see here<https://urldefense.com/v3/__https://github.com/lanl/bml/blob/67f84c34a3d429264abd8c492915f64f6e54c2bc/CMakeLists.txt*L238-L245__;Iw!!Bt8fGhp8LhKGRg!A8rKQZi3hdG2P0LBkfVo6Bknwx2W7_ioXP9Qr5KOtb-M5qcfRVgWpRji_DzEpIRY-mhQgXyUDinSlg7oCUbBnk3F$>). This new behavior is fine with me, but I just wanted to make sure this is what you had planned. Or am I missing something?

**Comment by jeanlucf22** [comment]
Failing at build time is better than running on CPU when you think you are running on GPU. I like this change.

**Review by jeanlucf22 — APPROVED** [review]

**Comment by jmohdyusof** [comment]
I like the addition of BML_OFFLOAD_ARCH, do we still need to retain the separate cuda etc flags?

**Comment by oseikuffuor1** [comment]
> 

I like this change too!! Thanks @mewall.

**Review by oseikuffuor1 — APPROVED** [review]

**Comment by mewall** [comment]
We might be able to get rid of the BML_CUSPARSE and BML_ROCSPARSE flags there, as they require BML_OMP_OFFLOAD. The other flags control different kinds of builds where BML_OFFLOAD_ARCH might be undefined.


I might take a look at how to improve all the GPU logic and try to take a shot at it soon, since I've just been looking at all of these things for CUSPARSE and ROCSPARSE. I think things have improved a little recently, though.


________________________________
From: Jamal Mohd-Yusof ***@***.***>
Sent: Thursday, July 21, 2022 11:37:15 AM
To: lanl/bml
Cc: Wall, Michael E; Mention
Subject: [EXTERNAL] Re: [lanl/bml] Add rocSPARSE method for ellpack multiply (PR #645)


I like the addition of BML_OFFLOAD_ARCH, do we still need to retain the separate cuda etc flags?

**Comment by jmohdyusof** [comment]
Yeah, if it helps to hash things out I am happy to discuss. Since we might eventually have a performant native OpenMP offload code (or some other thing), then logically offload, offload_arch and cusparse/rocsparse might all be separate (e.g. DO offload to AMD, but DON'T use rocsparse)

**Review by nicolasbock — APPROVED** [review]

**Comment by mewall** [comment]
@nicolasbock I'm having trouble getting the Lint test to pass for src/C-interface/ellpack/bml_multiply_ellpack_typed.c

I'm using a local install of indent

[mewall@darwin-fe1 bml]$ indent --version
GNU indent 2.2.12

This gives a couple of errors but does generate an output file (I've seen these errors for a little while both for this file and bml_add_ellpack_typed.c)

[mewall@darwin-fe1 bml]$ indent -gnu -nut -i4 -bli0 -cli4 -ppi0 -cbi0 -npcs -bfda src/C-interface/ellpack/bml_multiply_ellpack_typed.c -o src/C-interface/ellpack/bml_multiply_ellpack_typed.c.indented
indent: src/C-interface/ellpack/bml_multiply_ellpack_typed.c:312: Error:Stmt nesting error.
indent: src/C-interface/ellpack/bml_multiply_ellpack_typed.c:488: Error:Stmt nesting error.

There's nothing in the diff output

[mewall@darwin-fe1 bml]$ diff -Naur src/C-interface/ellpack/bml_multiply_ellpack_typed.c src/C-interface/ellpack/bml_multiply_ellpack_typed.c.indented
[mewall@darwin-fe1 bml]$

Any ideas?

**Comment by mewall** [comment]
Thanks! I can do that on my local machine, but as far as we know we can't run docker on darwin. I just pushed a revision.


I think it would be good to be able to download patches for the failing files, that should make my workflow a lot easier...

________________________________
From: Nicolas Bock ***@***.***>
Sent: Thursday, July 21, 2022 12:56:12 PM
To: lanl/bml
Cc: Wall, Michael E; Mention
Subject: [EXTERNAL] Re: [lanl/bml] Add rocSPARSE method for ellpack multiply (PR #645)


Can you run docker? If so you can use

./scripts/run-local-docker-container.sh<https://urldefense.com/v3/__http://run-local-docker-container.sh__;!!Bt8fGhp8LhKGRg!DdUJiOVurySMXeYEMevggUgIC25uIaLfyhqamfPDBUUVyT6TqWwVoZFtV9QSriHRBvzfKiInTiDpSlnjA-QY3rCn$> ./build.sh<https://urldefense.com/v3/__http://build.sh__;!!Bt8fGhp8LhKGRg!DdUJiOVurySMXeYEMevggUgIC25uIaLfyhqamfPDBUUVyT6TqWwVoZFtV9QSriHRBvzfKiInTiDpSlnjA1dKJ_j7$> check_indent

To make this easier in the future I will modify the CI script in a separate PR so that you can download the failing files.

**Pull request merged**
