### PR TITLE
Fix MAGMA bug in bml_element_multiply_AB_dense

### PR DESCRIPTION
**Pull request by mewall**
The code had an assignment with incompatible types when using MAGMA. It wasn't compiling when using MAGMA.

The code was changed to fix this issue.

### CODE REVIEW

**Comment by mewall** [comment]
Hmm...the following tests are failing. I need to look into this some more before it's merged.

	313 - C-element_multiply-dense-single_real (Failed)
	314 - C-element_multiply-dense-double_real (Failed)
	315 - C-element_multiply-dense-single_complex (Failed)
	316 - C-element_multiply-dense-double_complex (Failed)
	630 - fortran-multiply-dense-single_real (Failed)
	631 - fortran-multiply-dense-double_real (Failed)
	632 - fortran-multiply-dense-single_complex (Failed)
	633 - fortran-multiply-dense-double_complex (Failed)

**Comment by jmohdyusof** [comment]
Where is it failing? It seems to be passing the tests for a lot of compilers?

**Comment by mewall** [comment]
It fails when the MAGMA code path is used. The CI tests don't exercise that code path.

________________________________
From: Jamal Mohd-Yusof ***@***.***>
Sent: Tuesday, January 25, 2022 5:05:01 PM
To: lanl/bml
Cc: Wall, Michael E; Author
Subject: [EXTERNAL] Re: [lanl/bml] Fix MAGMA bug in bml_element_multiply_AB_dense (PR #572)


Where is it failing? It seems to be passing the tests for a lot of compilers?

**Comment by jmohdyusof** [comment]
Ah, OK. Sorry

**Review by suemni — APPROVED** [review]

**Comment by ares201005** [comment]
ooops, I didn't test MAGM path.

**Comment by mewall** [comment]
Let's discuss this in today's meeting. I'm also seeing an issue with the multiply tests, which I'm guessing is unrelated.

________________________________
From: Yu Zhang ***@***.***>
Sent: Wednesday, January 26, 2022 9:55:35 AM
To: lanl/bml
Cc: Wall, Michael E; Author
Subject: [EXTERNAL] Re: [lanl/bml] Fix MAGMA bug in bml_element_multiply_AB_dense (PR #572)


ooops, I didn't test MAGM path.

**Review by nicolasbock — CHANGES_REQUESTED** [review]
I don't have access to a GPU and can't verify the actual change.

Please

1. Squash the 2 commits
2. Address the linter errors

Thanks!

**Comment by mewall** [comment]
Closing this request as this issue will be addressed by Yu.

**Pull request closed without merging**
