### PR TITLE
Ellblock optimization

### PR DESCRIPTION
**Pull request by jeanlucf22**
Optimize small matrix multiplications when libxsmm is not available

---
This change is [Reviewable](https://reviewable.io/reviews/lanl/bml/401)

### CODE REVIEW

**Comment by jeanlucf22** [comment]
@nicolasbock The option of using libxsmm has been in for a while, see build.sh

**Comment by nicolasbock** [comment]
Right @jeanlucf22 . What I meant to say is that the lines pertaining to `libxsmm` don't seem to be connected with the subject of the commit, i.e. "Unroll inner loop in functions". I presume that the `libxsmm_init()` and `libxsmm_finalize()` calls should be in the code but could you elaborate a little in the commit message to explain why those lines are added now and were missing before?

If the code didn't work before we are missing some test coverage in our CI. If that's the case, we should add a test for libxsmm. I can certainly help you there.

Thanks!

**Comment by jeanlucf22** [comment]
@nicolasbock true, the libxsmm_init and finalize don't really belong in this PR. I'll split the PR. It is not incorrect when they are missing. The init is just "an explicit initialization routine helps to avoid lazy initialization overhead when calling LIBXSMM for the first time".

**Comment by jeanlucf22** [comment]
@nicolasbock as far as testing is concerned, the use of libxsmm is not tested. That would require an extra build with libxsmm, or more...

**Comment by jeanlucf22** [comment]
@nicolasbock libxsmm related stuff has been removed (and merged with PR #402). Now ready to merge if you are happy with the changes

**Comment by nicolasbock** [comment]
That looks great @jeanlucf22 ! Thanks!

**Pull request merged**
