### PR TITLE
Changed README file

### PR DESCRIPTION
**Pull request by cnegre**
Updated README

---
This change is [Reviewable](https://reviewable.io/reviews/lanl/bml/406)

### CODE REVIEW

**Comment by nicolasbock** [comment]
### Proselint found issues

#### [README.md](/lanl/bml/tree/README-update/README.md)

Line | Message | Severity |
| --- | ----- | ----- |
220 | No paragraph should start with a 'But'. | warning


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by suemni — APPROVED** [review]

**Comment by jeanlucf22** [comment]
Please add myself and @oseikuffuor1  as contributors

**Comment by jeanlucf22** [comment]
Shall we add reference to BML 2018 paper?

**Review by nicolasbock — APPROVED** [review]
:+1:

**Pull request merged**
