### PR TITLE
Add RTD badge

### PR DESCRIPTION
**Pull request by nicolasbock**
Signed-off-by: Nicolas Bock <nicolasbock@gmail.com>

### CODE REVIEW

**Review by suemni — APPROVED** [review]

**Comment by jmohdyusof** [comment]
Doesn't it make sense to change the docs branch to be the default for RTD for now, so that you don't have to merge with master every time?

**Comment by nicolasbock** [comment]
RTD is building from `master`. Currently we don't have a separate `docs` branch.

I would prefer if we left the documentation in the `master` branch so that we don't have to sync branches to keep the documentation up to date.

**Comment by nicolasbock** [comment]
@jmohdyusof It turns out that RTD is using a really old `sphinx` version (`sphinx-1.8.6`) which I didn't catch when testing the documentation build locally. I have submitted lanl/bml#576 to address this.

**Comment by jmohdyusof** [comment]
> RTD is building from `master`. Currently we don't have a separate `docs` branch.
> 
> I would prefer if we left the documentation in the `master` branch so that we don't have to sync branches to keep the documentation up to date.

I was suggesting to make a docs branch and set RTD to use that temporarily so that you (and I?) can edit it on the fly to make docs work, then we can merge to master and set RTD to use master going forward. Otherwise every edit requires a pull request.

**Comment by nicolasbock** [comment]
Ok I see. I created a `docs` branch and set RTD to build from it.

**Comment by jmohdyusof** [comment]
Cool, let me know if you want me to help with hacking on that.

**Pull request merged**
