### PR TITLE
Disable CircleCI

### PR DESCRIPTION
**Pull request by nicolasbock**
Signed-off-by: Nicolas Bock <nicolasbock@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/lanl/bml/437)

### CODE REVIEW

**Comment by nicolasbock** [comment]
@jeanlucf22 Couuld you review this PR? Thanks!

**Review by jeanlucf22 — APPROVED** [review]
I approve, but I don't understand why it still tries to build the circleci tests and fails...

**Comment by nicolasbock** [comment]
CircleCI is still expecting a configuration file [1] which this PR removes. We also have to update the Circle CI configuration but I don't have enough power to do that.

[1] https://app.circleci.com/pipelines/github/lanl/bml/499/workflows/6c964bc2-e515-4655-925a-a4290e62433d/jobs/5886

**Comment by jeanlucf22** [comment]
Who can do that? @cnegre ?

**Comment by nicolasbock** [comment]
I suspect @junghans can. @junghans could you disable CircleCI builds for `bml`? Thanks!

**Comment by junghans** [comment]
Hopefully that works....I clicked stop building lanl/bml.

**Comment by nicolasbock** [comment]
Thanks @junghans !

**Pull request merged**
