### PR TITLE
A few more functions for distributed2d

### PR DESCRIPTION
**Pull request by jeanlucf22**

### CODE REVIEW

**Review by nicolasbock — APPROVED** [review]

**Review by nicolasbock — CHANGES_REQUESTED** [review]
Could you look into why [this](https://github.com/lanl/bml/pull/490/checks?check_run_id=2630610180#step:4:2778) is failing?

**Review by suemni — APPROVED** [review]

**Comment by jeanlucf22** [comment]
@nicolasbock There was actually a bug in the diagonalization function for the distributed2d format that we were not catching before. Just fixed it, and fixed the test too.

**Comment by nicolasbock** [comment]
> @nicolasbock There was actually a bug in the diagonalization function for the distributed2d format that we were not catching before. Just fixed it, and fixed the test too.

Nice!

There is still a memory leak in one of the tests: https://github.com/lanl/bml/pull/490/checks?check_run_id=2643057870#step:4:4114

Could you have a look?

Thanks!

**Review by nicolasbock — APPROVED** [review]
Thanks @jeanlucf22 !

**Pull request merged**
