### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by nicolasbock**
This change is [Reviewable](https://reviewable.io/reviews/lanl/bml/423)

### CODE REVIEW

**Comment by nicolasbock** [comment]
### Proselint found issues

#### [README.md](/lanl/bml/tree/README/README.md)

Line | Message | Severity |
| --- | ----- | ----- |
242 | No paragraph should start with a 'But'. | warning


<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by jmohdyusof** [comment]
But why not?

**Comment by nicolasbock** [comment]
> But why not?

Haha, good question 😄 We should maybe see whether we even want this linter to run.

**Comment by jmohdyusof** [comment]
Seriously, I think it is a good grammar suggestion for the most part. But trying to enforce good grammar in English is notoriously hard.

**Comment by nicolasbock** [comment]
@jmohdyusof Have a look at #426

**Comment by jmohdyusof** [comment]
I am not an authorized reviewer

**Comment by nicolasbock** [comment]
> I am not an authorized reviewer

Try now. If I did this correctly you should be added now.

**Review by jeanlucf22 — APPROVED** [review]

**Pull request merged**
