### PR TITLE
Fix functions/values used for multiply x2 test

### PR DESCRIPTION
**Pull request by jeanlucf22**

### CODE REVIEW

**Comment by jmohdyusof** [comment]
Should like 37 and 39 use the same format? I have no opinion on which is preferred (but happy to learn)

**Comment by jeanlucf22** [comment]
> Should like 37 and 39 use the same format? I have no opinion on which is preferred (but happy to learn)

The 'f' is for float only, not double (if I understand it right)

**Comment by jmohdyusof** [comment]
So is 2e-6 interpreted as a double?

**Comment by jeanlucf22** [comment]
> 

I believe so, that is why you do not see a warning for that one

**Comment by jmohdyusof** [comment]
This seems to be correct. I would prefer something like 2e-6f (but I am not sure it is allowed) just because I dislike having to count zeros

**Review by suemni — APPROVED** [review]

**Comment by nicolasbock** [comment]
With `gcc-12.2.0` I get the following:

```C
#include <stdlib.h>
#include <stdio.h>

int main() {
    printf("sizeof() = %lu\n", sizeof(1e-6f));
}
```

```console
gcc test.c && ./a.out 
sizeof() = 4
```

So it is possible to write the literal in `e` notation (for @jmohdyusof :smile:) and also force it to be `float`.

**Comment by nicolasbock** [comment]
I forgot to add that I would also prefer the 'e' notation. Counting zeros is error prone.

**Review by jmohdyusof — APPROVED** [review]
Approved, will test on Intel and Darwin

**Review by nicolasbock — APPROVED** [review]

**Pull request merged**
