### PR TITLE
Add test for bml_print_bml_matrix functions

### PR DESCRIPTION
**Pull request by jeanlucf22**
This change is [Reviewable](https://reviewable.io/reviews/lanl/bml/308)

### CODE REVIEW

**Comment by jeanlucf22** [comment]
Working on it. It passes all the tests on my local machine, so not an obvious bug...

**Comment by jmohdyusof** [comment]
I was trying to find where the print_matrix functions are defined. Which branch/file are they in?

**Comment by jeanlucf22** [comment]
Look at bml_utilities_* files.

**Comment by jmohdyusof** [comment]
The complex types are being cast to float/double respectively? Is that correct? Otherwise it is hard to see how it would differ since both use export_to_dense and print_dense.

**Comment by jeanlucf22** [comment]
Are you referring to the test function?

**Comment by jmohdyusof** [comment]
In bml_utilities, the complex matrices are initialized as real.

**Comment by jeanlucf22** [comment]
With this test, I am trying to check what is printed out to stdout by redirecting it to a file, which is printed out with a small number of digits. So precision is not really the issue. The main issue is to read complex numbers that look like 0.840+0.000i and compare those with _Complex type values. I am using a pretty loose tolerance of 10^-3 because of the small number of digits written out by function to be tested.

**Comment by nicolasbock** [comment]
In my local tests your tests are passing. Strange.

**Comment by nicolasbock** [comment]
I just realized that the `bml_random_matrix()` function only produces real valued matrices. Maybe not very useful for complex types.

**Comment by jeanlucf22** [comment]
One thing I noticed is that in the CI testing, two tests can be run simultaneously, and conflicts could happen with two tests trying to access the same file. My last fix is taking care of that.

**Comment by jeanlucf22** [comment]
> I just realized that the `bml_random_matrix()` function only produces real valued matrices. Maybe not very useful for complex types.

Indeed. I believe some tests need to be revisited and strengthened.

**Comment by jmohdyusof** [comment]
My point was that you are passing a complex matrix to a real type, so you are inserting extra zeros into the real matrix (the imaginary parts will appear in the alternating real outputs)

**Comment by nicolasbock** [comment]
> One thing I noticed is that in the CI testing, two tests can be run simultaneously, and conflicts could happen with two tests trying to access the same file. My last fix is taking care of that.

Ah, good catch. We are running the tests in parallel (see https://github.com/lanl/bml/blob/master/build.sh#L197). So you need to make sure you don't introduce race conditions. But it looks like your approach of naming the temporary files works. You could alternatively use `mktemp()`.

**Comment by jeanlucf22** [comment]
Still failing...

**Comment by nicolasbock** [comment]
The interesting thing is that the `dense` type passes.

**Comment by nicolasbock** [comment]
@jeanlucf22 I think I found the problem. Do you mind if I push my version?

**Comment by jeanlucf22** [comment]
Go ahead!

**Comment by nicolasbock** [comment]
Looks like an improvement. At this point the valgrind tests are failing, but the other ones aren't. I'll check what the issue with valgrind is.

**Comment by nicolasbock** [comment]
I don't quite understand the valgrind errors yet. They seem to be in `printf` for example, or they might be triggered inside `printf` by the arguments we are passing. It looks like your new test is uncovering some issues we hadn't noticed so far @jeanlucf22 ! Thanks! Once we fix those the code will be better :smile:

**Comment by jeanlucf22** [comment]
There was an obvious memory leak that I just fixed and pushed. Let see if there is more...

**Comment by nicolasbock** [comment]
Thanks @jeanlucf22 ! I think I found the rest. I just pushed another attempt.

**Comment by nicolasbock** [comment]
@jeanlucf22 I haven't fixed the last test and simply added some logic to skip it, but now all tests pass :smile:

In a follow up, we need to address the situation where the compiler does not support complex types and we map the complex types to the corresponding real types so we don't have to change the API. However, your test shows that this is not working everywhere correctly.

I don't want to block this PR until we fix `BML_COMPLEX=no` and I think it's fine to add the conditional skip for now.

**Comment by jeanlucf22** [comment]
Thanks @nicolasbock ! What was the main issue making the test failing for ellpack single_real for instance? Was the  fflush(stdout) that you added the key? Restoring stdout certainly makes it cleaner, but was it also required to make it work?

**Comment by nicolasbock** [comment]
No problem :smile: The issue was that when we build with `CMAKE_BUILD_TYPE=Debug` the `export` code printed a line to `stdout` which made the parsing fail. I removed the lines since they don't really add anything of value anyhow. I suppose we could have left them also but print to stderr instead.

You are right that restoring `stdout` wasn't really an issue.

**Pull request merged**
