### PR TITLE
Openmp 5.0 and gcc-9

### PR DESCRIPTION
**Pull request by nicolasbock**
Changes to fix the changes in `gcc-9` regarding `default(none)` data-sharing statements.

Fixes: #261 

---
This change is [Reviewable](https://reviewable.io/reviews/lanl/bml/262)

### CODE REVIEW

**Comment by junghans** [comment]
Could you tag a new release after that, so that we can include this fix in spack?

**Comment by nicolasbock** [comment]
Yes, will do.

**Comment by nicolasbock** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please use more than one word.<br />
e7203379be0581f338a9d530be5cd6f9808fd57c</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by nicolasbock** [comment]
I think I am getting there in terms of getting Travis-CI to work. Hopefully soon :smile:

**Comment by nicolasbock** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          1 Error
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please use more than one word.<br />
005bf116bc8dc5aa4e92ba736b7f7712c2cfd309</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by junghans** [comment]
Oh, yeah!

**Comment by nicolasbock** [comment]
Finally :smile:

**Comment by junghans** [comment]
Can you tag a release and I will do a version bump in spack.

**Comment by nicolasbock** [comment]
Of course. Here it is: https://github.com/lanl/bml/releases/tag/v1.3.1

**Comment by junghans** [comment]
https://github.com/spack/spack/pull/11856

**Pull request merged**
