### PR TITLE
Product of two matrices

### PR DESCRIPTION
**Pull request by ares201005**
add the product of two matrices, i.e., sum_{ij}A_{ij}B_{ij}.

---
This change is [Reviewable](https://reviewable.io/reviews/lanl/bml/412)

### CODE REVIEW

**Comment by nicolasbock** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Error">
          4 Errors
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please start subject with capital letter.<br />
4a942d21e0f653afc43b6cb82a8a5299a7dd0aac</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please start subject with capital letter.<br />
3cdba992c55be89e27a35039847c31d979ac37c4</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please limit commit subject line to 50 characters.<br />
3cdba992c55be89e27a35039847c31d979ac37c4</td>
    </tr>
    <tr>
      <td>:no_entry_sign:</td>
      <td data-sticky="false">Please remove period from end of commit subject line.<br />
3cdba992c55be89e27a35039847c31d979ac37c4</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Review by cnegre — APPROVED** [review]

**Review by nicolasbock — APPROVED** [review]
Thank you!

**Comment by nicolasbock** [comment]
@ares201005 , could you have a look at the [linter errors](https://github.com/lanl/bml/pull/412/checks?check_run_id=1456157081#step:6:2355) and fix those?

**Comment by ares201005** [comment]
> @ares201005 , could you have a look at the [linter errors](https://github.com/lanl/bml/pull/412/checks?check_run_id=1456157081#step:6:2355) and fix those?

Sure, I will fix them.

**Review by nicolasbock — CHANGES_REQUESTED** [review]
Thanks @ares201005 ! Colud you also add a test for the new function?

**Comment by ares201005** [comment]
> Thanks @ares201005 ! Colud you also add a test for the new function?

Good suggestion. will do it!

**Comment by nicolasbock** [comment]
Thanks @ares201005 ! Let me know if you have any questions regarding how to write such tests.

**Comment by nicolasbock** [comment]
Rebased

**Review by nicolasbock — APPROVED** [review]
Thanks!

**Comment by ares201005** [comment]
> Rebased

Thanks for fixing the linter issues. I forgot to do this.

**Comment by nicolasbock** [comment]
No worries :smile: Thanks for the PR!

**Pull request merged**
