### PR TITLE
Simplify offload code using BML_OFFLOAD_CHUNKS macro

### PR DESCRIPTION
**Pull request by mewall**

### CODE REVIEW

**Review by suemni — APPROVED** [review]

**Comment by mewall** [comment]
Builds and passes tests on Darwin volta-x86 NVIDIA GPU except the Fortran trace tests as described in issue #664
Builds and passes tests on crusher AMD GPU

@oseikuffuor1 Please test on IBM
@jmohdyusof Please test on Intel

**Comment by oseikuffuor1** [comment]
@mewall which paths are you testing in your build script? Are you testing with rocsparse capabilities turned on? On Summit with the IBM compiler, 93% of the tests passed. On Lassen, only 57% passed (but this matches how many tests passed with the BML master branch as well).

**Comment by mewall** [comment]
> @mewall which paths are you testing in your build script? Are you testing with rocsparse capabilities turned on? On Summit with the IBM compiler, 93% of the tests passed. On Lassen, only 57% passed (but this matches how many tests passed with the BML master branch as well).

It would be good to test it without cusparse so all of the offload code is exercised.

**Comment by oseikuffuor1** [comment]
> > @mewall which paths are you testing in your build script? Are you testing with rocsparse capabilities turned on? On Summit with the IBM compiler, 93% of the tests passed. On Lassen, only 57% passed (but this matches how many tests passed with the BML master branch as well).
> 
> It would be good to test it without cusparse so all of the offload code is exercised.
> 
> Which tests are failing on Summit?

Some fortran ones, ellpack copy, add, diagonalize, set_diagonal, threshold, trace, multiply_x2 and transpose. Can you share or post the options you have in your build script?

**Comment by mewall** [comment]
> > > @mewall which paths are you testing in your build script? Are you testing with rocsparse capabilities turned on? On Summit with the IBM compiler, 93% of the tests passed. On Lassen, only 57% passed (but this matches how many tests passed with the BML master branch as well).
> > 
> > 
> > It would be good to test it without cusparse so all of the offload code is exercised.
> > Which tests are failing on Summit?
> 
> Some fortran ones, ellpack copy, add, diagonalize, set_diagonal, threshold, trace, multiply_x2 and transpose. Can you share or post the options you have in your build script?

This is what I used for GNU compilers on an NVIDIA node

[mewall@darwin-fe1 bml]$ cat offload_build_darwin.sh
#!/bin/bash

# Make sure all the paths are correct

rm -r build
rm -r install

MY_PATH=$(pwd)

export CC=${CC:=gcc}
export FC=${FC:=gfortran}
export CXX=${CXX:=g++}
#export BLAS_VENDOR=${BLAS_VENDOR:=MKL}
export BLAS_LIBRARIES="-L${MKLROOT}/lib/intel64 -Wl,--no-as-needed -lmkl_intel_lp64 -lmkl_gnu_thread -lmkl_core -lgomp -lpthread -lm -ldl"
export BML_OPENMP=${BML_OPENMP:=yes}
export BML_OMP_OFFLOAD=${BML_OMP_OFFLOAD:=yes}
export BML_OFFLOAD_ARCH=${BML_OFFLOAD_ARCH:=NVIDIA}
export BML_MAGMA=${BML_MAGMA:=no}
export INSTALL_DIR=${INSTALL_DIR:="${MY_PATH}/install"}
export BML_TESTING=${BML_TESTING:=yes}
export CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE:=Release}
export EXTRA_CFLAGS=${EXTRA_CFLAGS:=""}
export EXTRA_LINK_FLAGS=${EXTRA_LINK_FLAGS:=""}
export CUDA_TOOLKIT_ROOT_DIR=${CUDA_ROOT}
export CMAKE_Fortran_FLAGS="-g -fopenmp -foffload=nvptx-none"
export CMAKE_C_FLAGS="-g -O3 -fopenmp -foffload=nvptx-none"
./build.sh install

**Comment by oseikuffuor1** [comment]
> > > > @mewall which paths are you testing in your build script? Are you testing with rocsparse capabilities turned on? On Summit with the IBM compiler, 93% of the tests passed. On Lassen, only 57% passed (but this matches how many tests passed with the BML master branch as well).
> > > 
> > > 
> > > It would be good to test it without cusparse so all of the offload code is exercised.
> > > Which tests are failing on Summit?
> > 
> > 
> > Some fortran ones, ellpack copy, add, diagonalize, set_diagonal, threshold, trace, multiply_x2 and transpose. Can you share or post the options you have in your build script?
> 
> This is what I used for GNU compilers on an NVIDIA node
> 
> [mewall@darwin-fe1 bml]$ cat offload_build_darwin.sh #!/bin/bash
> 
> rm -r build rm -r install
> 
> MY_PATH=$(pwd)
> 
> export CC=${CC:=gcc} export FC=${FC:=gfortran} export CXX=${CXX:=g++} #export BLAS_VENDOR=${BLAS_VENDOR:=MKL} export BLAS_LIBRARIES="-L${MKLROOT}/lib/intel64 -Wl,--no-as-needed -lmkl_intel_lp64 -lmkl_gnu_thread -lmkl_core -lgomp -lpthread -lm -ldl" export BML_OPENMP=${BML_OPENMP:=yes} export BML_OMP_OFFLOAD=${BML_OMP_OFFLOAD:=yes} export BML_OFFLOAD_ARCH=${BML_OFFLOAD_ARCH:=NVIDIA} export BML_MAGMA=${BML_MAGMA:=no} export INSTALL_DIR=${INSTALL_DIR:="${MY_PATH}/install"} export BML_TESTING=${BML_TESTING:=yes} export CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE:=Release} export EXTRA_CFLAGS=${EXTRA_CFLAGS:=""} export EXTRA_LINK_FLAGS=${EXTRA_LINK_FLAGS:=""} export CUDA_TOOLKIT_ROOT_DIR=${CUDA_ROOT} export CMAKE_Fortran_FLAGS="-g -fopenmp -foffload=nvptx-none" export CMAKE_C_FLAGS="-g -O3 -fopenmp -foffload=nvptx-none" ./build.sh install

Thanks @mewall. It looks like I was missing the offload_arch (and perhaps the BML_magma) options. The branch builds and passes all tests on lassen (IBM compilers with NVIDIA). On Summit, the same tests fail for both master and this branch, so I presume everything is ok. It is not clear to me why those tests are failing on summit and not on Lassen (I'll investigate), but it looks to me your changes are OK. Thanks again.

**Comment by mewall** [comment]
> > > > > @mewall which paths are you testing in your build script? Are you testing with rocsparse capabilities turned on? On Summit with the IBM compiler, 93% of the tests passed. On Lassen, only 57% passed (but this matches how many tests passed with the BML master branch as well).
> > > > 
> > > > 
> > > > It would be good to test it without cusparse so all of the offload code is exercised.
> > > > Which tests are failing on Summit?
> > > 
> > > 
> > > Some fortran ones, ellpack copy, add, diagonalize, set_diagonal, threshold, trace, multiply_x2 and transpose. Can you share or post the options you have in your build script?
> > 
> > 
> > This is what I used for GNU compilers on an NVIDIA node
> > [mewall@darwin-fe1 bml]$ cat offload_build_darwin.sh #!/bin/bash
> > rm -r build rm -r install
> > MY_PATH=$(pwd)
> > export CC=${CC:=gcc} export FC=${FC:=gfortran} export CXX=${CXX:=g++} #export BLAS_VENDOR=${BLAS_VENDOR:=MKL} export BLAS_LIBRARIES="-L${MKLROOT}/lib/intel64 -Wl,--no-as-needed -lmkl_intel_lp64 -lmkl_gnu_thread -lmkl_core -lgomp -lpthread -lm -ldl" export BML_OPENMP=${BML_OPENMP:=yes} export BML_OMP_OFFLOAD=${BML_OMP_OFFLOAD:=yes} export BML_OFFLOAD_ARCH=${BML_OFFLOAD_ARCH:=NVIDIA} export BML_MAGMA=${BML_MAGMA:=no} export INSTALL_DIR=${INSTALL_DIR:="${MY_PATH}/install"} export BML_TESTING=${BML_TESTING:=yes} export CMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE:=Release} export EXTRA_CFLAGS=${EXTRA_CFLAGS:=""} export EXTRA_LINK_FLAGS=${EXTRA_LINK_FLAGS:=""} export CUDA_TOOLKIT_ROOT_DIR=${CUDA_ROOT} export CMAKE_Fortran_FLAGS="-g -fopenmp -foffload=nvptx-none" export CMAKE_C_FLAGS="-g -O3 -fopenmp -foffload=nvptx-none" ./build.sh install
> 
> Thanks @mewall. It looks like I was missing the offload_arch (and perhaps the BML_magma) options. The branch builds and passes all tests on lassen (IBM compilers with NVIDIA). On Summit, the same tests fail for both master and this branch, so I presume everything is ok. It is not clear to me why those tests are failing on summit and not on Lassen (I'll investigate), but it looks to me your changes are OK. Thanks again.

Thanks Daniel!

**Review by oseikuffuor1 — APPROVED** [review]
Looks good to me. Thanks.

**Comment by jmohdyusof** [comment]
I don't think any of this is exercised on Aurora since they use separate flags? This looks like Toks' Intel CPU branches?

**Comment by mewall** [comment]
We should create a new script that uses the newer offload macros, and support the Intel architecture for the GPU in the CMakelists.txt file. I'll add an issue to the repo.

________________________________
From: Jamal Mohd-Yusof ***@***.***>
Sent: Monday, November 14, 2022 8:26:47 AM
To: lanl/bml
Cc: Wall, Michael E; Mention
Subject: [EXTERNAL] Re: [lanl/bml] Simplify offload code using BML_OFFLOAD_CHUNKS macro (PR #663)


I don't think any of this is exercised on Aurora since they use separate flags? This looks like Toks' Intel CPU branches?

**Comment by jmohdyusof** [comment]
Master branch builds and passes all tests. 
bml_offload_chunks_macro hangs on:
        Start 393: C-normalize-ellpack-single_real

**Comment by jmohdyusof** [comment]
Also, building master I see errors like:
/home/ac.jjamaludin/Aurora/bml/tests/C-tests/multiply_matrix_x2_typed.c:31:28: warning: using floating point absolute value function 'fabs' when argument is of complex type [-Wabsolute-value]
            C[i * N + j] = fabs(val) > threshold ? val : 0.;
                           ^
/home/ac.jjamaludin/Aurora/bml/tests/C-tests/multiply_matrix_x2_typed.c:31:28: note: use function 'cabsf' instead
            C[i * N + j] = fabs(val) > threshold ? val : 0.;
                           ^~~~
                           cabsf
/home/ac.jjamaludin/Aurora/bml/tests/C-tests/multiply_matrix_x2_typed.c:54:30: warning: floating-point comparison is always true; constant cannot be represented exactly in type 'float' [-Wliteral-range]
        if (ABS(A[i] - B[i]) > ABS_TOL)

**Comment by jmohdyusof** [comment]
Indeed that seems to work. It would be nice to get the build_iris_offload_oneapi and build_mkl_gpu scripts to converge more, since the libraries should be mostly the same

**Comment by jmohdyusof** [comment]
As written, the new macro is really BML_USE_CHUNKS or something like that, since there is an additional flag needed to actually do offload?

**Review by jeanlucf22 — APPROVED** [review]

**Comment by jeanlucf22** [comment]
let's merge this one

**Review by nicolasbock — APPROVED** [review]

**Pull request merged**
